##写法
#
#Request:
#  "parm":
#    papi: "%diarymorepapi_judger%"  #需要判断的变量
#    case:
#      default: "trmenu open MainMenu"  #变量值为default
#      Gen8: "dragoncore opengui %player% Gen8/MainMenu/MainMenu"  #变量值为Gen8
#      Gen9: "dragoncore opengui %player% Gen9/MainMenu/MainMenu"  #变量值为Gen9
#
Request:
  MainMenu:
    papi: "%diarymorepapi_judger%"
    case:
      default: "trmenu open MainMenu"
      Gen8: "dragoncore opengui %player% Gen8/MainMenu/MainMenu"
      Gen9: "dragoncore opengui %player% Gen9/MainMenu/MainMenu"